source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/zhangxiaoshan618/podSpecsExercise.git'
use_frameworks!

target 'STNetworks_Example' do
  pod 'STNetworks/Base', :path => '../'
  pod 'STNetworks/Category', :path => '../'
  pod 'Networks'

  target 'STNetworks_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  pod 'FBSnapshotTestCase' , '~> 2.1.4'
  pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
